services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    restart: always
    command: "azurite --blobHost 127.0.0.1 --blobPort 10000 --queueHost 127.0.0.1 --queuePort 10001 --tableHost 127.0.0.1 --tablePort 10002 --location /workspace"
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - ./azurite:/workspace

  rpa-mit-notification:
    build:
      context: .
    image: rpa-mit-notification
    container_name: rpa-mit-notification
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      FUNCTIONS_WORKER_RUNTIME: dotnet-isolated
      AzureWebJobsStorage: ${AzureWebJobsStorage}
      QueueConnectionString: ${QueueConnectionString}
      EventQueueName: ${EventQueueName}
      NotificationQueueName: ${NotificationQueueName}
      TableConnectionString: ${TableConnectionString}
      NotificationTableName: ${NotificationTableName}
      AzureWebJobsSecretStorageType: ${AzureWebJobsSecretStorageType}
      NotifyApiKey: ${NotifyApiKey}
      TriggerTimerInterval: ${TriggerTimerInterval}
      templatesRequesterApproval: ${templatesRequesterApproval}
      templatesRequesterApproved: ${templatesRequesterApproved}
      templatesRequesterRejected: ${templatesRequesterRejected}
      templatesApproverApproval: ${templatesApproverApproval}
      templatesApproverApproved: ${templatesApproverApproved}
      templatesApproverRejected: ${templatesApproverRejected}
      templatesError: ${templatesError}
      templatesUploaded: ${templatesUploaded}

    depends_on:
        - azurite