services:
  azurite:
      image: mcr.microsoft.com/azure-storage/azurite
      container_name: aft-backend-azurite
      hostname: azurite
      restart: always
      command: 'azurite --loose --blobHost 0.0.0.0 --blobPort 10000 --queueHost 0.0.0.0 --queuePort 10001 --tableHost 0.0.0.0 --tablePort 10002'
      ports:
        - 10000:10000
        - 10001:10001
        - 10002:10002
  rpa-mit-notification:
    build:
      context: .
    image: rpa-mit-notification
    container_name: rpa-mit-notification
    environment:
      APPINSIGHTS_CLOUDROLE: rpa-mit-notification-local
      FUNCTIONS_WORKER_RUNTIME: dotnet-isolated
      AzureWebJobsStorage: UseDevelopmentStorage=true
      QueueConnectionString: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://host.docker.internal:10000/devstoreaccount1;QueueEndpoint=http://host.docker.internal:10001/devstoreaccount1;TableEndpoint=http://host.docker.internal:1002/devstoreaccount1;
      TableConnectionString: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://host.docker.internal:10000/devstoreaccount1;QueueEndpoint=http://host.docker.internal:10001/devstoreaccount1;TableEndpoint=http://host.docker.internal:1002/devstoreaccount1;
      AzureWebJobsQueueConnectionString: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://host.docker.internal:10000/devstoreaccount1;QueueEndpoint=http://host.docker.internal:10001/devstoreaccount1;TableEndpoint=http://host.docker.internal:1002/devstoreaccount1;
      EventQueueName: event
      AzureWebJobsSecretStorageType: files
      NotifyApiKey:
      TriggerTimerInterval: 0 */2 * * * *
      PartitionKey: MIT_Notifications
      templatesapproval: 8b70257a-a41c-4260-b9ce-2c6596246fb0
      templatesapproved: 30e785fe-75c7-40cd-aced-8d0856ff57ac
      templateserror: 5019017c-ac20-42bb-9fad-d72ed135d5bb
      templatesrejected: b7b06564-4a73-4a94-94e1-61ac58fbc7d2
      templatesupload: 88709ce9-b2b4-4175-a8fa-d0cf354e58b6
      schemasBPS: steve.dickinson@defra.gov.uk
      schemasAP: steve.dickinson@defra.gov.uk
    depends_on:
      - azurite
