environment: development
name: rpa-mit-notification
namespace: ffc-rpa
workstream: ffc-rpa
image: rpa-mit-notification

labels: {}

aadPodIdentity: true

appInsights:
  key:

azureIdentity:
  clientID: 0a393aa3-c85c-41f0-a0c6-a947116e5a77
  resourceID: /subscriptions/cd4e9a00-99d8-45a2-98bb-7648ef12c26d/resourcegroups/SNDFFCAKSRG1001/providers/Microsoft.ManagedIdentity/userAssignedIdentities/rpa-mit-notification

containerConfigMap:
  name: rpa-mit-notification-config-map

containerSecret:
  name: rpa-mit-notification-container-secret
  type: Opaque

deployment:
  cpuThreshold: 80
  memoryThreshold: 80
  minReadySeconds: 0
  minReplicas: 1
  maxReplicas: 1
  priorityClassName: default
  replicas: 1
  restartPolicy: Always

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 120Mi
  requestCpu: 5m
  limitMemory: 120Mi
  limitCpu: 120m
  port: 3000
  functionsWorkerRuntime: dotnet-isolated
  azureWebJobsSecretStorageType: files
  triggerTimerInterval: 0 */2 * * * *
  partitionKey: MIT_Notifications
  templatesApproval: 8b70257a-a41c-4260-b9ce-2c6596246fb0
  templatesApproved: 30e785fe-75c7-40cd-aced-8d0856ff57ac
  templatesError: 5019017c-ac20-42bb-9fad-d72ed135d5bb
  templatesRejected: b7b06564-4a73-4a94-94e1-61ac58fbc7d2
  templatesUpload: 88709ce9-b2b4-4175-a8fa-d0cf354e58b6
  schemasBPS: jeremy.barnsley@defra.gov.uk
  schemasAP: jeremy.barnsley@defra.gov.uk
  serviceBusNotificationConnectionString__fullyQualifiedNamespace: SNDFFCINFSB1001.servicebus.windows.net
  serviceBusNotificationQueueName: rpa-mit-notification
  serviceBusEventConnectionString__fullyQualifiedNamespace: SNDFFCINFSB1001.servicebus.windows.net
  serviceBusEventQueueName: rpa-mit-events
  notifyApiKey: secret
  tableConnectionString: secret
  azureWebJobsStorage: secret

service:
  port: 80
  type: ClusterIP

ingress:
  class: nginx
  endpoint: rpa-mit-notification
  server: value.replaced.from.app.config

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 120
  periodSeconds: 30
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 120
  periodSeconds: 30
  failureThreshold: 3