environment: development
name: rpa-mit-notification
namespace: ffc-rpa
workstream: ffc-rpa
image: rpa-mit-notification

labels: {}

aadPodIdentity: true

appInsights:
  key:

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID

containerConfigMap:
  name: rpa-mit-notification-config-map

containerSecret:
  name: rpa-mit-notification-container-secret
  type: Opaque

deployment:
  cpuThreshold: 80
  memoryThreshold: 80
  minReadySeconds: 0
  minReplicas: 1
  maxReplicas: 1
  priorityClassName: default
  replicas: 1
  restartPolicy: Always

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 120Mi
  requestCpu: 5m
  limitMemory: 120Mi
  limitCpu: 120m
  port: 3000
  functionsWorkerRuntime: dotnet-isolated
  azureWebJobsSecretStorageType: files
  triggerTimerInterval: 0 */2 * * * *
  templatesApproval: 8b70257a-a41c-4260-b9ce-2c6596246fb0
  templatesApproved: 30e785fe-75c7-40cd-aced-8d0856ff57ac
  templatesError: 5019017c-ac20-42bb-9fad-d72ed135d5bb
  templatesRejected: b7b06564-4a73-4a94-94e1-61ac58fbc7d2
  templatesUpload: 88709ce9-b2b4-4175-a8fa-d0cf354e58b6
  schemasBPS: jeremy.barnsley@defra.gov.uk
  schemasAP: jeremy.barnsley@defra.gov.uk
  notifyApiKey: secret
  azureWebJobsStorage: secret
  notificationQueueName: rpa-mit-invoicenotification
  notificationTableName: rpamitinvoicenotification

service:
  port: 80
  type: ClusterIP

ingress:
  class: nginx
  endpoint: rpa-mit-notification
  server: value.replaced.from.app.config

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 60
  periodSeconds: 30
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 60
  periodSeconds: 30
  failureThreshold: 3