- key: AzureWebJobsStorage
  value: "{{servicename}}-AzureWebJobsStorage"  
  type: "keyvault"

- key: QueueConnectionString
  value: "{{servicename}}-QueueConnectionString"  
  type: "keyvault"

- key: EventQueueName
  value: "{{servicename}}-EventQueueName"
  type: "keyvault"

- key: NotificationQueueName
  value: "{{servicename}}-NotificationQueueName"  
  type: "keyvault"

- key: TableConnectionString
  value: "{{servicename}}-TableConnectionString"  
  type: "keyvault"

- key: NotificationTableName
  value: "{{servicename}}-NotificationTableName"  
  type: "keyvault"

- key: AzureWebJobsSecretStorageType
  value: "{{servicename}}-AzureWebJobsSecretStorageType"  
  type: "keyvault"

- key: NotifyApiKey
  value: "{{servicename}}-NotifyApiKey"  
  type: "keyvault"
  
- key: TriggerTimerInterval
  value: "{{servicename}}-TriggerTimerInterval"  
  type: "keyvault"

- key: templatesRequesterApproval
  value: "{{servicename}}-templatesRequesterApproval"  
  type: "keyvault"

- key: templatesRequesterApproved
  value: "{{servicename}}-templatesRequesterApproved"  
  type: "keyvault"

- key: templatesRequesterRejected
  value: "{{servicename}}-templatesRequesterRejected"  
  type: "keyvault"

- key: templatesApproverApproval
  value: "{{servicename}}-templatesApproverApproval"  
  type: "keyvault"

- key: templatesApproverApproved
  value: "{{servicename}}-templatesApproverApproved"  
  type: "keyvault"

- key: templatesApproverRejected
  value: "{{servicename}}-templatesApproverRejected"  
  type: "keyvault"

- key: templatesError
  value: "{{servicename}}-templatesError"  
  type: "keyvault"

- key: templatesUploaded
  value: "{{servicename}}-templatesUploaded"  
  type: "keyvault"