- key: AzureWebJobsStorage
  value: "{{AzureWebJobsStorage}}"  
- key: QueueConnectionString
  value: "{{QueueConnectionString}}"  
- key: EventQueueName
  value: "{{EventQueueName}}"
- key: NotificationQueueName
  value: "{{NotificationQueueName}}"  
- key: TableConnectionString
  value: "{{TableConnectionString}}"  
- key: NotificationTableName
  value: "{{NotificationTableName}}"  
# - key: AzureWebJobsSecretStorageType
#   value: "{{AzureWebJobsSecretStorageType}}"  
- key: NotifyApiKey
  value: "{{NotifyApiKey}}"  
- key: TriggerTimerInterval
  value: "{{TriggerTimerInterval}}"  
- key: templatesRequesterApproval
  value: "{{templatesRequesterApproval}}"  
- key: templatesRequesterApproved
  value: "{{templatesRequesterApproved}}"  
- key: templatesRequesterRejected
  value: "{{templatesRequesterRejected}}"  
- key: templatesApproverApproval
  value: "{{templatesApproverApproval}}"  
- key: templatesApproverApproved
  value: "{{templatesApproverApproved}}"  
- key: templatesApproverRejected
  value: "{{templatesApproverRejected}}"  
- key: templatesError
  value: "{{templatesError}}"  
- key: templatesUploaded
  value: "{{templatesUploaded}}"  