{{- include "ffc-helm-library.container-secret" (list . "rpa-mit-notification.container-secret") -}}
{{- define "rpa-mit-notification.container-secret" -}}
stringData:
  {{- if .Values.appInsights.key }}
  APPINSIGHTS_INSTRUMENTATIONKEY: {{ quote .Values.appInsights.key }}
  {{- end }}
  AzureWebJobsStorage: {{ quote .Values.container.azureWebJobsStorage }}
  ServiceBusEventConnectionString: {{ quote .Values.container.serviceBusEventConnectionString }}
  ServiceBusNotificationConnectionString: {{ quote .Values.container.serviceBusNotificationConnectionString }}
  TableConnectionString: {{ quote .Values.container.tableConnectionString }}
  NotifyApiKey: {{ quote .Values.container.notifyApiKey }}
{{- end -}}
